# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceX iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VPopup', :path => '/Users/vestel/Desktop/V-Popup-iOS-master'
end
